"use client";

import { useCallback, useEffect, useRef, useState, type CSSProperties } from "react";
import { Download, RotateCcw, Trash2, Trophy, Upload } from "lucide-react";
import { Dialog,DialogClose,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog";
type Slip={name:string;x:number;y:number;vx:number;vy:number;a:number;va:number;w:number;h:number;color:string};
type Ticket={name:string;number:number};
const samples:string[]=[];
const colors=["#fff4b8","#c8f3ff","#ffd5e5","#d9ffc8","#eee0ff"];
function randomIndex(length:number){const range=0x100000000,limit=range-(range%length),v=new Uint32Array(1);do crypto.getRandomValues(v);while(v[0]>=limit);return v[0]%length}
const MAX_PER_PERSON=100000,MAX_TOTAL=250000;
function parseTicketCount(value:string){const text=value.trim();if(!/^\d+$/.test(text)&&!/^\d{1,3}(,\d{3})+$/.test(text))return null;const count=Number(text.replaceAll(",",""));return Number.isSafeInteger(count)&&count>0?count:null}
function expandEntries(value:string,firstTicketText:string){const firstTicket=parseTicketCount(firstTicketText);if(!firstTicket)return{tickets:[] as Ticket[],error:"Enter a valid first automatic ticket number."};const specs:{name:string;count:number;start?:number;end?:number}[]=[];for(const raw of value.split(/\r?\n/)){const entry=raw.trim();if(!entry)continue;const manual=entry.match(/^(.+?)\s+#\s*([\d,]+)\s*[-–]\s*([\d,]+)$/),weighted=entry.match(/^(.+?)\s+[×x]\s*([\d,]+)$/i);if(manual){const start=parseTicketCount(manual[2]),end=parseTicketCount(manual[3]);if(!start||!end||end<start)return{tickets:[] as Ticket[],error:`“${entry}” has an invalid ticket range.`};const count=end-start+1;if(count>MAX_PER_PERSON)return{tickets:[] as Ticket[],error:`${manual[1].trim()} has ${count.toLocaleString()} tickets. The per-person limit is ${MAX_PER_PERSON.toLocaleString()}.`};specs.push({name:manual[1].trim(),count,start,end});continue}if(weighted){const count=parseTicketCount(weighted[2]);if(!count)return{tickets:[] as Ticket[],error:`“${weighted[2]}” is not a valid ticket count. Use commas in groups of three, such as 50,000.`};if(count>MAX_PER_PERSON)return{tickets:[] as Ticket[],error:`${weighted[1].trim()} has ${count.toLocaleString()} tickets. The per-person limit is ${MAX_PER_PERSON.toLocaleString()}.`};specs.push({name:weighted[1].trim(),count});continue}if(/\s[×x]\s|\s#\s/.test(entry))return{tickets:[] as Ticket[],error:`“${entry}” is not formatted correctly. Use Bob × 50,000 or Bob #45,580-45,599.`};specs.push({name:entry,count:1})}const total=specs.reduce((sum,s)=>sum+s.count,0);if(total>MAX_TOTAL)return{tickets:[] as Ticket[],error:`This would exceed the ${MAX_TOTAL.toLocaleString()}-ticket raffle limit.`};const tickets:Ticket[]=[],used=new Set<number>();for(const spec of specs.filter(s=>s.start!==undefined)){for(let number=spec.start!;number<=spec.end!;number++){if(used.has(number))return{tickets:[] as Ticket[],error:`Ticket #${number.toLocaleString()} is assigned more than once.`};used.add(number);tickets.push({name:spec.name,number})}}let next=firstTicket;for(const spec of specs.filter(s=>s.start===undefined)){for(let i=0;i<spec.count;i++){while(used.has(next))next++;used.add(next);tickets.push({name:spec.name,number:next++})}}return{tickets,error:null}}

export default function Home(){
 const canvasRef=useRef<HTMLCanvasElement>(null),fileInputRef=useRef<HTMLInputElement>(null),slipsRef=useRef<Slip[]>([]),spinningRef=useRef(false),movingRef=useRef(false),drumAngleRef=useRef(0),drumSpeedRef=useRef(0),drawRef=useRef(0),frameRef=useRef(0);
 const [text,setText]=useState(samples.join("\n")),[names,setNames]=useState(samples),[original,setOriginal]=useState(samples),[ticketNumbers,setTicketNumbers]=useState(samples.map((_,i)=>i+1)),[originalTicketNumbers,setOriginalTicketNumbers]=useState(samples.map((_,i)=>i+1));
 const [winner,setWinner]=useState<string|null>(null),[winnerNumber,setWinnerNumber]=useState<number|null>(null),[history,setHistory]=useState<string[]>([]),[spinning,setSpinning]=useState(false),[message,setMessage]=useState("Add entries to begin."),[celebrating,setCelebrating]=useState(false);
 const [spinSeconds,setSpinSeconds]=useState(4),[firstTicket,setFirstTicket]=useState("1"),[entryMode,setEntryMode]=useState<"auto"|"manual">("auto"),[quickName,setQuickName]=useState(""),[quickCount,setQuickCount]=useState("1"),[manualStart,setManualStart]=useState(""),[manualEnd,setManualEnd]=useState(""),[error,setError]=useState<string|null>(null);
 const seedSlips=useCallback((list:string[])=>{movingRef.current=false;slipsRef.current=list.slice(0,80).map((name,i)=>({name,x:320+(Math.random()-.5)*230,y:215+Math.random()*125,vx:0,vy:0,a:(Math.random()-.5)*.7,va:0,w:Math.min(108,Math.max(66,34+name.length*7)),h:28,color:colors[i%colors.length]}))},[]);
 useEffect(()=>seedSlips(names),[names,seedSlips]);
 useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext("2d")!;let last=performance.now();
  const tick=(now:number)=>{const dt=Math.min(2,(now-last)/16.67);last=now;const cx=320,cy=225,radius=174;ctx.clearRect(0,0,640,470);const glow=ctx.createRadialGradient(cx,cy,30,cx,cy,200);glow.addColorStop(0,"#203256");glow.addColorStop(1,"#0b1428");ctx.fillStyle=glow;ctx.beginPath();ctx.arc(cx,cy,radius+7,0,Math.PI*2);ctx.fill();const rainbow=ctx.createConicGradient(drumAngleRef.current,cx,cy);["#ff4d6d","#ff9f1c","#ffe66d","#4ee58b","#46c7ff","#8d65ff","#ff4dba","#ff4d6d"].forEach((color,i)=>rainbow.addColorStop(i/7,color));ctx.strokeStyle=rainbow;ctx.shadowColor=spinningRef.current?`hsl(${(now*.12)%360} 95% 65%)`:"transparent";ctx.shadowBlur=spinningRef.current?24:0;ctx.lineWidth=10;ctx.stroke();ctx.shadowBlur=0;
   if(movingRef.current){drumAngleRef.current+=drumSpeedRef.current*dt;if(!spinningRef.current)drumSpeedRef.current*=.982}
   for(const s of slipsRef.current){if(movingRef.current){if(spinningRef.current){const dx=s.x-cx,dy=s.y-cy;s.vx+=(-dy*.0028+(Math.random()-.5)*.55)*dt;s.vy+=(dx*.0028+(Math.random()-.5)*.55)*dt;s.va+=(Math.random()-.5)*.025}s.vy+=(spinningRef.current ? .095 : .16)*dt;const drag=spinningRef.current ? .994 : .96;s.vx*=drag;s.vy*=drag;s.va*=spinningRef.current ? .985 : .94;s.x+=s.vx*dt;s.y+=s.vy*dt;s.a+=s.va*dt;const dx=s.x-cx,dy=s.y-cy,dist=Math.hypot(dx,dy),edge=radius-Math.max(s.w,s.h)*.48;if(dist>edge){const nx=dx/dist,ny=dy/dist;s.x=cx+nx*edge;s.y=cy+ny*edge;const dot=s.vx*nx+s.vy*ny;if(dot>0){const bounce=spinningRef.current?1.65:1.18;s.vx-=bounce*dot*nx;s.vy-=bounce*dot*ny}if(spinningRef.current)s.va+=(Math.random()-.5)*.12;else{s.vx*=.78;s.vy*=.62;s.va*=.7}}}ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.a);ctx.fillStyle=s.color;ctx.strokeStyle="#18213a";ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(-s.w/2,-s.h/2,s.w,s.h,6);ctx.fill();ctx.stroke();ctx.fillStyle="#17213a";ctx.font="700 13px system-ui";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(s.name.length>14?s.name.slice(0,13)+"…":s.name,0,1);ctx.restore()}
   const cageAngle=drumAngleRef.current;ctx.strokeStyle="rgba(255,255,255,.16)";ctx.lineWidth=2;for(let i=0;i<12;i++){const a=cageAngle+i*Math.PI/6;ctx.beginPath();ctx.moveTo(cx+Math.cos(a)*28,cy+Math.sin(a)*28);ctx.lineTo(cx+Math.cos(a)*(radius-5),cy+Math.sin(a)*(radius-5));ctx.stroke()}const marker=cageAngle+.18;ctx.fillStyle="#fff0a8";ctx.beginPath();ctx.arc(cx+Math.cos(marker)*(radius-15),cy+Math.sin(marker)*(radius-15),8,0,Math.PI*2);ctx.fill();ctx.fillStyle="#f8ba43";ctx.beginPath();ctx.arc(cx,cy,20,0,Math.PI*2);ctx.fill();frameRef.current=requestAnimationFrame(tick)};frameRef.current=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frameRef.current)},[]);
 const applyEntries=(source:string)=>{const result=expandEntries(source,firstTicket);if(result.error){setError(result.error);setMessage("Could not load the entries.");return}const tickets=result.tickets;if(!tickets.length){setError("Add at least one name first.");return}const parsedNames=tickets.map(t=>t.name),parsedNumbers=tickets.map(t=>t.number);drawRef.current++;spinningRef.current=false;movingRef.current=false;setSpinning(false);setNames(parsedNames);setOriginal(parsedNames);setTicketNumbers(parsedNumbers);setOriginalTicketNumbers(parsedNumbers);setWinner(null);setWinnerNumber(null);setHistory([]);setMessage(`${tickets.length.toLocaleString()} tickets loaded.`)};
 const load=()=>applyEntries(text);
 const quickAdd=()=>{const person=quickName.trim();if(!person){setError("Enter a name to add tickets.");return}let line="";if(entryMode==="auto"){const count=parseTicketCount(quickCount);if(!count){setError("Enter a valid ticket count. Commas must be in groups of three, such as 50,000.");return}if(count>MAX_PER_PERSON){setError(`Enter no more than ${MAX_PER_PERSON.toLocaleString()} tickets per person.`);return}line=`${person} × ${count.toLocaleString()}`}else{const start=parseTicketCount(manualStart),end=parseTicketCount(manualEnd);if(!start||!end||end<start){setError("Enter a valid starting and ending ticket number.");return}if(end-start+1>MAX_PER_PERSON){setError(`A manual range can contain no more than ${MAX_PER_PERSON.toLocaleString()} tickets.`);return}line=`${person} #${start.toLocaleString()}-${end.toLocaleString()}`}const next=text.trim()?`${text.trim()}\n${line}`:line;setText(next);setQuickName("");setQuickCount("1");setManualStart("");setManualEnd("");applyEntries(next)};
 const spin=()=>{if(spinning||!names.length)return;const drawId=++drawRef.current,pickedIndex=randomIndex(names.length),picked=names[pickedIndex],pickedNumber=ticketNumbers[pickedIndex];setCelebrating(false);for(const s of slipsRef.current){s.vx+=(Math.random()-.5)*7;s.vy-=2+Math.random()*6;s.va+=(Math.random()-.5)*.28}movingRef.current=true;drumSpeedRef.current=.075;setSpinning(true);spinningRef.current=true;setWinner(null);setWinnerNumber(null);setMessage("The names are tumbling…");setTimeout(()=>{if(drawRef.current!==drawId)return;spinningRef.current=false;setMessage("The drum is slowing down…");setTimeout(()=>{if(drawRef.current!==drawId)return;movingRef.current=false;drumSpeedRef.current=0;for(const s of slipsRef.current){s.vx=0;s.vy=0;s.va=0}setWinner(picked);setWinnerNumber(pickedNumber);setCelebrating(true);setTimeout(()=>{if(drawRef.current===drawId)setCelebrating(false)},7800);setHistory(h=>[`${picked} — Ticket #${pickedNumber.toLocaleString()}`,...h]);setMessage(`${picked} wins with ticket #${pickedNumber.toLocaleString()}!`);setSpinning(false)},2800)},spinSeconds*1000)};
 const removeWinner=()=>{if(!winner||winnerNumber===null)return;const at=ticketNumbers.indexOf(winnerNumber),nextNames=names.filter((_,i)=>i!==at),nextNumbers=ticketNumbers.filter((_,i)=>i!==at);setNames(nextNames);setTicketNumbers(nextNumbers);setWinner(null);setWinnerNumber(null);setMessage(`${nextNames.length.toLocaleString()} tickets remain.`)};
 const reset=()=>{drawRef.current++;spinningRef.current=false;movingRef.current=false;setSpinning(false);setNames(original);setTicketNumbers(originalTicketNumbers);setHistory([]);setWinner(null);setWinnerNumber(null);setMessage("Raffle reset. Ready for a spin.")};
 const exportRaffle=()=>{if(spinning){setError("Wait for the current drawing to finish before exporting.");return}const checked=expandEntries(text,firstTicket);if(checked.error){setError(`Fix the raffle before exporting: ${checked.error}`);return}const backup={format:"raffle-drum-backup",version:1,exportedAt:new Date().toISOString(),entries:text,settings:{firstTicket,spinSeconds},history};const blob=new Blob([JSON.stringify(backup,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`raffle-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);setMessage("Raffle backup downloaded.")};
 const importRaffle=async(file:File|undefined)=>{if(!file)return;if(spinning){setError("Wait for the current drawing to finish before importing.");return}if(file.size>2_000_000){setError("That backup file is too large. Choose a Raffle Drum JSON backup under 2 MB.");return}try{const data=JSON.parse(await file.text());if(data?.format!=="raffle-drum-backup"||data?.version!==1||typeof data.entries!=="string"||typeof data.settings?.firstTicket!=="string")throw new Error("This is not a compatible Raffle Drum backup.");const importedSpin=Number(data.settings.spinSeconds);if(!Number.isInteger(importedSpin)||importedSpin<2||importedSpin>20)throw new Error("The backup contains an invalid spin-time setting.");const result=expandEntries(data.entries,data.settings.firstTicket);if(result.error)throw new Error(result.error);if(!result.tickets.length)throw new Error("The backup does not contain any tickets.");const importedNames=result.tickets.map(t=>t.name),importedNumbers=result.tickets.map(t=>t.number),importedHistory=Array.isArray(data.history)?data.history.filter((x:unknown)=>typeof x==="string").slice(0,1000):[];drawRef.current++;movingRef.current=false;spinningRef.current=false;setSpinning(false);setText(data.entries);setFirstTicket(data.settings.firstTicket);setSpinSeconds(importedSpin);setNames(importedNames);setOriginal(importedNames);setTicketNumbers(importedNumbers);setOriginalTicketNumbers(importedNumbers);setHistory(importedHistory);setWinner(null);setWinnerNumber(null);setMessage(`${importedNames.length.toLocaleString()} tickets restored from backup.`)}catch(reason){setError(reason instanceof Error?reason.message:"The backup could not be read.")}};
 return <main className="app-shell">
  <header><div><p className="eyebrow">FAIR DRAW • LIVE PHYSICS</p><h1>Raffle Drum</h1></div></header>
  <div className="workspace">
   <section className="drum-card"><canvas ref={canvasRef} width={640} height={470} aria-label="Raffle tickets tumbling in a drum"/><div className="stand"><i/><i/></div><button className="spin" onClick={spin} disabled={spinning||!names.length}>{spinning?"TUMBLING…":"SPIN THE DRUM"}</button><div className="status drum-status" aria-live="polite"><span className={spinning?"dot active":"dot"}/>{message}</div></section>
   <aside>
    <section className="panel">
     <div className="panel-title"><h2>Raffle entries</h2><span>{names.length.toLocaleString()} tickets loaded</span></div>
     <div className="backup-actions"><button onClick={exportRaffle} disabled={spinning}><Download/>Export raffle</button><button onClick={()=>fileInputRef.current?.click()} disabled={spinning}><Upload/>Import raffle</button><input ref={fileInputRef} type="file" accept="application/json,.json" hidden onChange={e=>{void importRaffle(e.target.files?.[0]);e.target.value=""}}/></div>
     <div className="quick-add"><div className="quick-heading"><h3>Quick add tickets</h3><div className="mode-switch"><button className={entryMode==="auto"?"selected":""} onClick={()=>setEntryMode("auto")}>Automatic</button><button className={entryMode==="manual"?"selected":""} onClick={()=>setEntryMode("manual")}>Manual range</button></div></div><div className={entryMode==="manual"?"quick-grid manual":"quick-grid"}><label><span>Name</span><input value={quickName} onChange={e=>setQuickName(e.target.value)} placeholder="Bob"/></label>{entryMode==="auto"?<label><span>Tickets</span><input inputMode="numeric" value={quickCount} onChange={e=>setQuickCount(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")quickAdd()}} placeholder="50,000"/></label>:<><label><span>First #</span><input inputMode="numeric" value={manualStart} onChange={e=>setManualStart(e.target.value)} placeholder="45,580"/></label><label><span>Last #</span><input inputMode="numeric" value={manualEnd} onChange={e=>setManualEnd(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")quickAdd()}} placeholder="45,599"/></label></>}<button onClick={quickAdd}>Add tickets</button></div><p style={{color:"#7f89a2",fontSize:".72rem",margin:"7px 0 0"}}>Automatic numbering skips ticket numbers already used by manual ranges.</p></div>
     <label className="list-label" htmlFor="entries">Entry list <small>Bob × 50,000 or Bob #45,580-45,599</small></label>
     <textarea id="entries" value={text} onChange={e=>setText(e.target.value)} aria-label="Raffle entries" placeholder={"EXAMPLES — replace these with your entries:\n\nAlice\n→ 1 ticket with an automatic number\n\nBob × 50\n→ 50 tickets with automatic numbers\n\nCarol #45,580-45,599\n→ 20 tickets using that exact range"}/>
     <button className="load" onClick={load}>Load entries</button>
    </section>
    <section className="panel settings"><div className="panel-title"><h2>Settings</h2><strong>{spinSeconds} seconds</strong></div><label htmlFor="first-ticket">First automatic ticket #</label><input className="number-setting" id="first-ticket" inputMode="numeric" value={firstTicket} onChange={e=>setFirstTicket(e.target.value)}/><label htmlFor="spin-time">Spin time</label><input id="spin-time" type="range" min="2" max="20" step="1" value={spinSeconds} onChange={e=>setSpinSeconds(Number(e.target.value))}/><div className="range-labels"><span>2 sec</span><span>20 sec</span></div></section>
    <button className="reset" onClick={reset}><RotateCcw/>Reset raffle</button>
   </aside>
  </div>
  {history.length>0&&<section className="history"><h2>Winner history</h2><div>{history.map((n,i)=><span key={`${n}-${i}`}><b>{history.length-i}</b>{n}</span>)}</div></section>}
  <footer>Each ticket has an equal chance. A person entered 50 times has 50 tickets in the secure random draw.</footer>
  <Dialog open={!!error} onOpenChange={open=>{if(!open)setError(null)}}><DialogContent showCloseButton={false} className="border-[#2a3a5d] bg-[#15213d] text-[#f6f7fb] sm:max-w-md"><DialogHeader><DialogTitle>Couldn&apos;t load tickets</DialogTitle><DialogDescription className="text-[#aab2c7]">{error}</DialogDescription></DialogHeader><DialogFooter><DialogClose asChild><button className="popup-ok">OK</button></DialogClose></DialogFooter></DialogContent></Dialog>
  {celebrating&&<div className="confetti-layer" aria-hidden="true"><span className="pop-flash left"/><span className="pop-flash right"/>{Array.from({length:160},(_,i)=>{const left=i%2===0,slot=Math.floor(i/2),origin=left?10:90,targetX=4+((slot*47+(left?7:19))%92),targetY=4+((slot*29)%48),tx=targetX-origin,ty=targetY-88,sway=left?1:-1;return <i key={i} className={i%5===0?"confetti-round":i%7===0?"confetti-streamer":""} style={{left:`${origin}%`,top:"88%","--mx":`${tx*.36}vw`,"--my":`${ty*.36}vh`,"--tx":`${tx}vw`,"--ty":`${ty}vh`,"--s1x":`${tx+sway*(4+(i%5))}vw`,"--s1y":`${ty+18}vh`,"--s2x":`${tx-sway*(4+(i%6))}vw`,"--s2y":`${ty+38}vh`,"--s3x":`${tx+sway*(3+(i%4))}vw`,"--s3y":`${ty+60}vh`,"--fx":`${tx-sway*(1+(i%3))}vw`,"--spin":`${540+(i%8)*115}deg`,animationDelay:`${(i%5)*.008}s`,animationDuration:`${5.7+(i%8)*.12}s`,backgroundColor:["#ff315f","#ffd21f","#00e39c","#31b8ff","#a95cff","#ff7417"][i%6]} as CSSProperties}/>})}</div>}
  <Dialog open={!!winner} onOpenChange={open=>{if(!open){setWinner(null);setWinnerNumber(null);setCelebrating(false)}}}><DialogContent showCloseButton={false} className="z-[60] border-[#f8ba43]/60 bg-[#15213d] text-center text-[#f6f7fb] sm:max-w-md"><DialogHeader className="items-center text-center"><Trophy className="size-12 text-[#f8ba43]"/><DialogTitle className="text-sm tracking-[.2em] text-[#aab2c7]">WINNER</DialogTitle><DialogDescription className="break-words text-4xl font-black text-[#f6f7fb]">{winner}</DialogDescription><p className="winning-ticket">Ticket #{winnerNumber?.toLocaleString()}</p></DialogHeader><DialogFooter className="sm:justify-center"><button className="popup-remove" onClick={removeWinner}><Trash2 className="size-4"/>Remove ticket</button><DialogClose asChild><button className="popup-ok">OK</button></DialogClose></DialogFooter></DialogContent></Dialog>
 </main>
}
